[target.armv7-linux-androideabi]
linker = "/Users/johndoe/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi33-clang++"
rustflags = ["-C", "link-arg=-L/Users/johndoe/StudioProjects/hbat/libgcc-shim"]
[target.i686-linux-android]
linker = "/Users/johndoe/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android33-clang++"
rustflags = ["-C", "link-arg=-L/Users/johndoe/StudioProjects/hbat/libgcc-shim"]
[target.x86_64-linux-android]
linker = "/Users/johndoe/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android33-clang++"
rustflags = ["-C", "link-arg=-L/Users/johndoe/StudioProjects/hbat/libgcc-shim"]
[target.aarch64-linux-android]
linker = "/Users/johndoe/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang++"
rustflags = ["-C", "link-arg=-L/Users/johndoe/StudioProjects/hbat/libgcc-shim"]
